# Generated by Django 4.2.16 on 2024-11-23 02:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_date", models.DateField(unique=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("constitutional_members", models.IntegerField()),
                ("members_in_good_standing", models.IntegerField()),
                ("active_income_based", models.IntegerField()),
                ("active_monthly", models.IntegerField()),
                ("active_yearly", models.IntegerField()),
                ("active_other", models.IntegerField()),
                ("members", models.IntegerField()),
                ("lapsed_expired", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="member",
            name="monthly_dues_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("never", "Never"),
                    ("2mo_plus_failed", "2 Months Plus Failed"),
                    ("lapsed", "Lapsed"),
                    ("active", "Active"),
                    ("manual", "Manual"),
                    ("past_due", "Past Due"),
                    ("canceled_by_failure", "Canceled by Failure"),
                    ("canceled_by_admin", "Canceled by Admin"),
                    ("canceled_by_processor", "Canceled by Processor"),
                    ("canceled_by_user", "Canceled by User"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="union_member",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Yes, current union member", "Yes, current union member"),
                    ("Yes, retired union member", "Yes, retired union member"),
                    ("No, not a union member", "No, not a union member"),
                    ("No, but former union member", "No, but former union member"),
                    (
                        "Currently organizing my workplace",
                        "Currently organizing my workplace",
                    ),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="yearly_dues_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("never", "Never"),
                    ("2mo_plus_failed", "2 Months Plus Failed"),
                    ("lapsed", "Lapsed"),
                    ("active", "Active"),
                    ("manual", "Manual"),
                    ("past_due", "Past Due"),
                    ("canceled_by_failure", "Canceled by Failure"),
                    ("canceled_by_admin", "Canceled by Admin"),
                    ("canceled_by_processor", "Canceled by Processor"),
                    ("canceled_by_user", "Canceled by User"),
                ],
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalMembershipCount",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("list_date", models.DateField(db_index=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("constitutional_members", models.IntegerField()),
                ("members_in_good_standing", models.IntegerField()),
                ("active_income_based", models.IntegerField()),
                ("active_monthly", models.IntegerField()),
                ("active_yearly", models.IntegerField()),
                ("active_other", models.IntegerField()),
                ("members", models.IntegerField()),
                ("lapsed_expired", models.IntegerField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical membership count",
                "verbose_name_plural": "historical membership counts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMember",
            fields=[
                ("first_name", models.CharField(max_length=255)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("do_not_call", models.BooleanField(default=False)),
                ("p2ptext_optout", models.BooleanField(default=False)),
                ("best_phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "mobile_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("home_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("work_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("join_date", models.DateField()),
                ("xdate", models.DateField()),
                (
                    "membership_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("one-time", "One-time"),
                            ("yearly", "Yearly"),
                            ("monthly", "Monthly"),
                            ("income-based", "Income-based"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "monthly_dues_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("never", "Never"),
                            ("2mo_plus_failed", "2 Months Plus Failed"),
                            ("lapsed", "Lapsed"),
                            ("active", "Active"),
                            ("manual", "Manual"),
                            ("past_due", "Past Due"),
                            ("canceled_by_failure", "Canceled by Failure"),
                            ("canceled_by_admin", "Canceled by Admin"),
                            ("canceled_by_processor", "Canceled by Processor"),
                            ("canceled_by_user", "Canceled by User"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "yearly_dues_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("never", "Never"),
                            ("2mo_plus_failed", "2 Months Plus Failed"),
                            ("lapsed", "Lapsed"),
                            ("active", "Active"),
                            ("manual", "Manual"),
                            ("past_due", "Past Due"),
                            ("canceled_by_failure", "Canceled by Failure"),
                            ("canceled_by_admin", "Canceled by Admin"),
                            ("canceled_by_processor", "Canceled by Processor"),
                            ("canceled_by_user", "Canceled by User"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "membership_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Lapsed", "Lapsed"),
                            ("Member", "Member"),
                            ("Member in Good Standing", "Member in Good Standing"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "memb_status_letter",
                    models.CharField(
                        blank=True, choices=[("L", "L"), ("M", "M")], max_length=2
                    ),
                ),
                (
                    "union_member",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Yes, current union member", "Yes, current union member"),
                            ("Yes, retired union member", "Yes, retired union member"),
                            ("No, not a union member", "No, not a union member"),
                            (
                                "No, but former union member",
                                "No, but former union member",
                            ),
                            (
                                "Currently organizing my workplace",
                                "Currently organizing my workplace",
                            ),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("union_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "union_local",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("accommodations", models.TextField(blank=True, null=True)),
                (
                    "student_yes_no",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Yes, college student", "Yes, college student"),
                            ("Yes, graduate student", "Yes, graduate student"),
                            ("Yes, high school student", "Yes, high school student"),
                            ("No", "No"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "student_school_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mailing_pref",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("Membership card only", "Membership card only"),
                            ("No", "No"),
                        ],
                        max_length=255,
                    ),
                ),
                ("address1", models.CharField(max_length=255)),
                ("address2", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(default="MA", max_length=2)),
                ("zip", models.CharField(max_length=10)),
                ("country", models.CharField(default="United States", max_length=50)),
                ("actionkit_id", models.IntegerField(db_index=True)),
                ("dsa_chapter", models.CharField(default="Worcester", max_length=50)),
                (
                    "ydsa_chapter",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("new_member_past_month", models.BooleanField(default=False)),
                ("list_date", models.DateField()),
                (
                    "discord_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "discord_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Member", "Member"),
                            ("Member in Good Standing", "Member in Good Standing"),
                            ("Visiting Member", "Visiting Member"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("vaccinated", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("do_not_text", models.BooleanField(default=False)),
                ("do_not_email", models.BooleanField(default=False)),
                ("in_chapter", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical member",
                "verbose_name_plural": "historical members",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
