# Generated by Django 4.2.16 on 2024-12-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "membership",
            "0002_membershipcount_alter_member_monthly_dues_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmember",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
