# Generated by Django 4.2.16 on 2024-12-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0003_alter_historicalmember_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmember",
            name="address1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="address1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
