# Generated by Django 4.2.16 on 2024-12-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0004_alter_historicalmember_address1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmember",
            name="home_phone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="mobile_phone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="work_phone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="home_phone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="mobile_phone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="work_phone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
