# Generated by Django 4.2.16 on 2024-12-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0005_alter_historicalmember_home_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="zip_code_list",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="monthly_dues_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("never", "Never"),
                    ("2mo_plus_failed", "2 Months Plus Failed"),
                    ("lapsed", "Lapsed"),
                    ("active", "Active"),
                    ("manual", "Manual"),
                    ("overdue", "Overdue"),
                    ("past_due", "Past Due"),
                    ("canceled_by_failure", "Canceled by Failure"),
                    ("canceled_by_admin", "Canceled by Admin"),
                    ("canceled_by_processor", "Canceled by Processor"),
                    ("canceled_by_user", "Canceled by User"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="yearly_dues_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("never", "Never"),
                    ("2mo_plus_failed", "2 Months Plus Failed"),
                    ("lapsed", "Lapsed"),
                    ("active", "Active"),
                    ("manual", "Manual"),
                    ("overdue", "Overdue"),
                    ("past_due", "Past Due"),
                    ("canceled_by_failure", "Canceled by Failure"),
                    ("canceled_by_admin", "Canceled by Admin"),
                    ("canceled_by_processor", "Canceled by Processor"),
                    ("canceled_by_user", "Canceled by User"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="monthly_dues_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("never", "Never"),
                    ("2mo_plus_failed", "2 Months Plus Failed"),
                    ("lapsed", "Lapsed"),
                    ("active", "Active"),
                    ("manual", "Manual"),
                    ("overdue", "Overdue"),
                    ("past_due", "Past Due"),
                    ("canceled_by_failure", "Canceled by Failure"),
                    ("canceled_by_admin", "Canceled by Admin"),
                    ("canceled_by_processor", "Canceled by Processor"),
                    ("canceled_by_user", "Canceled by User"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="yearly_dues_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("never", "Never"),
                    ("2mo_plus_failed", "2 Months Plus Failed"),
                    ("lapsed", "Lapsed"),
                    ("active", "Active"),
                    ("manual", "Manual"),
                    ("overdue", "Overdue"),
                    ("past_due", "Past Due"),
                    ("canceled_by_failure", "Canceled by Failure"),
                    ("canceled_by_admin", "Canceled by Admin"),
                    ("canceled_by_processor", "Canceled by Processor"),
                    ("canceled_by_user", "Canceled by User"),
                ],
                max_length=255,
            ),
        ),
    ]
