# Generated by Django 4.2.16 on 2025-06-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0006_region_zip_code_list_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmember",
            name="in_chapter",
        ),
        migrations.RemoveField(
            model_name="member",
            name="in_chapter",
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="membership_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("one-time", "One-time"),
                    ("yearly", "Yearly"),
                    ("monthly", "Monthly"),
                    ("income-based", "Income-based"),
                    ("unknown", "Unknown"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="monthly_dues_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("never", "Never"),
                    ("2mo_plus_failed", "2 Months Plus Failed"),
                    ("lapsed", "Lapsed"),
                    ("active", "Active"),
                    ("manual", "Manual"),
                    ("overdue", "Overdue"),
                    ("past_due", "Past Due"),
                    ("canceled_by_failure", "Canceled by Failure"),
                    ("canceled_by_admin", "Canceled by Admin"),
                    ("canceled_by_processor", "Canceled by Processor"),
                    ("canceled_by_user", "Canceled by User"),
                    ("unknown", "Unknown"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="yearly_dues_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("never", "Never"),
                    ("2mo_plus_failed", "2 Months Plus Failed"),
                    ("lapsed", "Lapsed"),
                    ("active", "Active"),
                    ("manual", "Manual"),
                    ("overdue", "Overdue"),
                    ("past_due", "Past Due"),
                    ("canceled_by_failure", "Canceled by Failure"),
                    ("canceled_by_admin", "Canceled by Admin"),
                    ("canceled_by_processor", "Canceled by Processor"),
                    ("canceled_by_user", "Canceled by User"),
                    ("unknown", "Unknown"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="membership_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("one-time", "One-time"),
                    ("yearly", "Yearly"),
                    ("monthly", "Monthly"),
                    ("income-based", "Income-based"),
                    ("unknown", "Unknown"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="monthly_dues_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("never", "Never"),
                    ("2mo_plus_failed", "2 Months Plus Failed"),
                    ("lapsed", "Lapsed"),
                    ("active", "Active"),
                    ("manual", "Manual"),
                    ("overdue", "Overdue"),
                    ("past_due", "Past Due"),
                    ("canceled_by_failure", "Canceled by Failure"),
                    ("canceled_by_admin", "Canceled by Admin"),
                    ("canceled_by_processor", "Canceled by Processor"),
                    ("canceled_by_user", "Canceled by User"),
                    ("unknown", "Unknown"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="yearly_dues_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("never", "Never"),
                    ("2mo_plus_failed", "2 Months Plus Failed"),
                    ("lapsed", "Lapsed"),
                    ("active", "Active"),
                    ("manual", "Manual"),
                    ("overdue", "Overdue"),
                    ("past_due", "Past Due"),
                    ("canceled_by_failure", "Canceled by Failure"),
                    ("canceled_by_admin", "Canceled by Admin"),
                    ("canceled_by_processor", "Canceled by Processor"),
                    ("canceled_by_user", "Canceled by User"),
                    ("unknown", "Unknown"),
                ],
                max_length=255,
            ),
        ),
    ]
