# Generated by Django 3.2.6 on 2024-11-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MembershipFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("processed", models.BooleanField()),
                ("processed_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
